version: '3.8'

services:
  mhgacha-app:
    build: .
    container_name: MHWIldsGacha
    ports:
      - "2470:2470"
    volumes:
      - ./services:/app/services
      - .:/app
    environment:
      - PYTHONPATH=/app/backend/services/cards-service/src
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

  db:
    image: postgres:alpine  
    container_name: mydb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
